version: "3.8"
services:
  NodeChat:
    image: b0ltz205/nodeqr:lts
    build: .
    container_name: qrgenerator
    ports:
      - "80:3000"
    environment:
      - PORT=3000
    volumes:
      - ./:/app
